

# This file was *autogenerated* from the file factor.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0 = Integer(0); _sage_const_1 = Integer(1)
from time import time

with open('test.in', 'r') as f:
    cnt = _sage_const_0 
    start = time()

    for l in f:
        n = int(l)
        assert(len(factor(n)) > _sage_const_1 )
        cnt += _sage_const_1 

    print(cnt / (time() - start))

