cc_binary(
  name = "absl-btree",
  deps = ["@com_google_absl//absl/container:btree"],
  srcs = ["absl-btree.cc"],
)

cc_binary(
  name = "absl",
  deps = ["@com_google_absl//absl/container:btree"],
  srcs = ["absl.cc", "btree.hh"],
)
